server.port=${PORT:8080}

# Conexión corregida
spring.datasource.url=jdbc:${MYSQL_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate y Dialecto moderno
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Tiempo de espera para evitar crashes al arrancar
spring.datasource.hikari.connection-timeout=30000